/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* This file should be compiled with 6c/8c.  */
#pragma dynimport _ _ "flame.so"

#include "runtime.h"
#include "cgocall.h"

#ifdef _64BIT
#define SWIG_PARM_SIZE 8
#else
#define SWIG_PARM_SIZE 4
#endif

#pragma dynimport _wrap_IntArray_array_set _wrap_IntArray_array_set ""
extern void (*_wrap_IntArray_array_set)(void*);
static void (*x_wrap_IntArray_array_set)(void*) = _wrap_IntArray_array_set;

void
·_swig_wrap_IntArray_array_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_IntArray_array_set, &p);
}



#pragma dynimport _wrap_IntArray_array_get _wrap_IntArray_array_get ""
extern void (*_wrap_IntArray_array_get)(void*);
static void (*x_wrap_IntArray_array_get)(void*) = _wrap_IntArray_array_get;

void
·_swig_wrap_IntArray_array_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_IntArray_array_get, &p);
}



#pragma dynimport _wrap_IntArray_size_set _wrap_IntArray_size_set ""
extern void (*_wrap_IntArray_size_set)(void*);
static void (*x_wrap_IntArray_size_set)(void*) = _wrap_IntArray_size_set;

void
·_swig_wrap_IntArray_size_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_IntArray_size_set, &p);
}



#pragma dynimport _wrap_IntArray_size_get _wrap_IntArray_size_get ""
extern void (*_wrap_IntArray_size_get)(void*);
static void (*x_wrap_IntArray_size_get)(void*) = _wrap_IntArray_size_get;

void
·_swig_wrap_IntArray_size_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_IntArray_size_get, &p);
}



#pragma dynimport _wrap_IntArray_bufsize_set _wrap_IntArray_bufsize_set ""
extern void (*_wrap_IntArray_bufsize_set)(void*);
static void (*x_wrap_IntArray_bufsize_set)(void*) = _wrap_IntArray_bufsize_set;

void
·_swig_wrap_IntArray_bufsize_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_IntArray_bufsize_set, &p);
}



#pragma dynimport _wrap_IntArray_bufsize_get _wrap_IntArray_bufsize_get ""
extern void (*_wrap_IntArray_bufsize_get)(void*);
static void (*x_wrap_IntArray_bufsize_get)(void*) = _wrap_IntArray_bufsize_get;

void
·_swig_wrap_IntArray_bufsize_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_IntArray_bufsize_get, &p);
}



#pragma dynimport _wrap_new_IntArray _wrap_new_IntArray ""
extern void (*_wrap_new_IntArray)(void*);
static void (*x_wrap_new_IntArray)(void*) = _wrap_new_IntArray;

void
·_swig_wrap_new_IntArray(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_IntArray, &p);
}



#pragma dynimport _wrap_delete_IntArray _wrap_delete_IntArray ""
extern void (*_wrap_delete_IntArray)(void*);
static void (*x_wrap_delete_IntArray)(void*) = _wrap_delete_IntArray;

void
·_swig_wrap_delete_IntArray(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_IntArray, &p);
}



#pragma dynimport _wrap_IndexFloat_index_set _wrap_IndexFloat_index_set ""
extern void (*_wrap_IndexFloat_index_set)(void*);
static void (*x_wrap_IndexFloat_index_set)(void*) = _wrap_IndexFloat_index_set;

void
·_swig_wrap_IndexFloat_index_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_IndexFloat_index_set, &p);
}



#pragma dynimport _wrap_IndexFloat_index_get _wrap_IndexFloat_index_get ""
extern void (*_wrap_IndexFloat_index_get)(void*);
static void (*x_wrap_IndexFloat_index_get)(void*) = _wrap_IndexFloat_index_get;

void
·_swig_wrap_IndexFloat_index_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_IndexFloat_index_get, &p);
}



#pragma dynimport _wrap_IndexFloat_value_set _wrap_IndexFloat_value_set ""
extern void (*_wrap_IndexFloat_value_set)(void*);
static void (*x_wrap_IndexFloat_value_set)(void*) = _wrap_IndexFloat_value_set;

void
·_swig_wrap_IndexFloat_value_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_IndexFloat_value_set, &p);
}



#pragma dynimport _wrap_IndexFloat_value_get _wrap_IndexFloat_value_get ""
extern void (*_wrap_IndexFloat_value_get)(void*);
static void (*x_wrap_IndexFloat_value_get)(void*) = _wrap_IndexFloat_value_get;

void
·_swig_wrap_IndexFloat_value_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_IndexFloat_value_get, &p);
}



#pragma dynimport _wrap_new_IndexFloat _wrap_new_IndexFloat ""
extern void (*_wrap_new_IndexFloat)(void*);
static void (*x_wrap_new_IndexFloat)(void*) = _wrap_new_IndexFloat;

void
·_swig_wrap_new_IndexFloat(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_IndexFloat, &p);
}



#pragma dynimport _wrap_delete_IndexFloat _wrap_delete_IndexFloat ""
extern void (*_wrap_delete_IndexFloat)(void*);
static void (*x_wrap_delete_IndexFloat)(void*) = _wrap_delete_IndexFloat;

void
·_swig_wrap_delete_IndexFloat(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_IndexFloat, &p);
}



#pragma dynimport _wrap_PartialQuickSort _wrap_PartialQuickSort ""
extern void (*_wrap_PartialQuickSort)(void*);
static void (*x_wrap_PartialQuickSort)(void*) = _wrap_PartialQuickSort;

void
·_swig_wrap_PartialQuickSort(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_PartialQuickSort, &p);
}



#pragma dynimport _wrap_Flame_Euclidean _wrap_Flame_Euclidean ""
extern void (*_wrap_Flame_Euclidean)(void*);
static void (*x_wrap_Flame_Euclidean)(void*) = _wrap_Flame_Euclidean;

void
·Flame_Euclidean(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_Euclidean, &p);
}



#pragma dynimport _wrap_Flame_Cosine _wrap_Flame_Cosine ""
extern void (*_wrap_Flame_Cosine)(void*);
static void (*x_wrap_Flame_Cosine)(void*) = _wrap_Flame_Cosine;

void
·Flame_Cosine(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_Cosine, &p);
}



#pragma dynimport _wrap_Flame_Pearson _wrap_Flame_Pearson ""
extern void (*_wrap_Flame_Pearson)(void*);
static void (*x_wrap_Flame_Pearson)(void*) = _wrap_Flame_Pearson;

void
·Flame_Pearson(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_Pearson, &p);
}



#pragma dynimport _wrap_Flame_UCPearson _wrap_Flame_UCPearson ""
extern void (*_wrap_Flame_UCPearson)(void*);
static void (*x_wrap_Flame_UCPearson)(void*) = _wrap_Flame_UCPearson;

void
·Flame_UCPearson(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_UCPearson, &p);
}



#pragma dynimport _wrap_Flame_SQPearson _wrap_Flame_SQPearson ""
extern void (*_wrap_Flame_SQPearson)(void*);
static void (*x_wrap_Flame_SQPearson)(void*) = _wrap_Flame_SQPearson;

void
·Flame_SQPearson(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_SQPearson, &p);
}



#pragma dynimport _wrap_Flame_DotProduct _wrap_Flame_DotProduct ""
extern void (*_wrap_Flame_DotProduct)(void*);
static void (*x_wrap_Flame_DotProduct)(void*) = _wrap_Flame_DotProduct;

void
·Flame_DotProduct(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_DotProduct, &p);
}



#pragma dynimport _wrap_Flame_Covariance _wrap_Flame_Covariance ""
extern void (*_wrap_Flame_Covariance)(void*);
static void (*x_wrap_Flame_Covariance)(void*) = _wrap_Flame_Covariance;

void
·Flame_Covariance(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_Covariance, &p);
}



#pragma dynimport _wrap_Flame_Manhattan _wrap_Flame_Manhattan ""
extern void (*_wrap_Flame_Manhattan)(void*);
static void (*x_wrap_Flame_Manhattan)(void*) = _wrap_Flame_Manhattan;

void
·Flame_Manhattan(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_Manhattan, &p);
}



#pragma dynimport _wrap_Flame_CosineDist _wrap_Flame_CosineDist ""
extern void (*_wrap_Flame_CosineDist)(void*);
static void (*x_wrap_Flame_CosineDist)(void*) = _wrap_Flame_CosineDist;

void
·Flame_CosineDist(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_CosineDist, &p);
}



#pragma dynimport _wrap_Flame_PearsonDist _wrap_Flame_PearsonDist ""
extern void (*_wrap_Flame_PearsonDist)(void*);
static void (*x_wrap_Flame_PearsonDist)(void*) = _wrap_Flame_PearsonDist;

void
·Flame_PearsonDist(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_PearsonDist, &p);
}



#pragma dynimport _wrap_Flame_UCPearsonDist _wrap_Flame_UCPearsonDist ""
extern void (*_wrap_Flame_UCPearsonDist)(void*);
static void (*x_wrap_Flame_UCPearsonDist)(void*) = _wrap_Flame_UCPearsonDist;

void
·Flame_UCPearsonDist(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_UCPearsonDist, &p);
}



#pragma dynimport _wrap_Flame_SQPearsonDist _wrap_Flame_SQPearsonDist ""
extern void (*_wrap_Flame_SQPearsonDist)(void*);
static void (*x_wrap_Flame_SQPearsonDist)(void*) = _wrap_Flame_SQPearsonDist;

void
·Flame_SQPearsonDist(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_SQPearsonDist, &p);
}



#pragma dynimport _wrap_Flame_DotProductDist _wrap_Flame_DotProductDist ""
extern void (*_wrap_Flame_DotProductDist)(void*);
static void (*x_wrap_Flame_DotProductDist)(void*) = _wrap_Flame_DotProductDist;

void
·Flame_DotProductDist(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_DotProductDist, &p);
}



#pragma dynimport _wrap_Flame_CovarianceDist _wrap_Flame_CovarianceDist ""
extern void (*_wrap_Flame_CovarianceDist)(void*);
static void (*x_wrap_Flame_CovarianceDist)(void*) = _wrap_Flame_CovarianceDist;

void
·Flame_CovarianceDist(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_CovarianceDist, &p);
}



#pragma dynimport _wrap_DST_USER _wrap_DST_USER ""
extern void (*_wrap_DST_USER)(void*);
static void (*x_wrap_DST_USER)(void*) = _wrap_DST_USER;

void
·_swig_getDST_USER(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DST_USER, &p);
}



#pragma dynimport _wrap_DST_EUCLID _wrap_DST_EUCLID ""
extern void (*_wrap_DST_EUCLID)(void*);
static void (*x_wrap_DST_EUCLID)(void*) = _wrap_DST_EUCLID;

void
·_swig_getDST_EUCLID(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DST_EUCLID, &p);
}



#pragma dynimport _wrap_DST_COSINE _wrap_DST_COSINE ""
extern void (*_wrap_DST_COSINE)(void*);
static void (*x_wrap_DST_COSINE)(void*) = _wrap_DST_COSINE;

void
·_swig_getDST_COSINE(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DST_COSINE, &p);
}



#pragma dynimport _wrap_DST_PEARSON _wrap_DST_PEARSON ""
extern void (*_wrap_DST_PEARSON)(void*);
static void (*x_wrap_DST_PEARSON)(void*) = _wrap_DST_PEARSON;

void
·_swig_getDST_PEARSON(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DST_PEARSON, &p);
}



#pragma dynimport _wrap_DST_UC_PEARSON _wrap_DST_UC_PEARSON ""
extern void (*_wrap_DST_UC_PEARSON)(void*);
static void (*x_wrap_DST_UC_PEARSON)(void*) = _wrap_DST_UC_PEARSON;

void
·_swig_getDST_UC_PEARSON(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DST_UC_PEARSON, &p);
}



#pragma dynimport _wrap_DST_SQ_PEARSON _wrap_DST_SQ_PEARSON ""
extern void (*_wrap_DST_SQ_PEARSON)(void*);
static void (*x_wrap_DST_SQ_PEARSON)(void*) = _wrap_DST_SQ_PEARSON;

void
·_swig_getDST_SQ_PEARSON(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DST_SQ_PEARSON, &p);
}



#pragma dynimport _wrap_DST_DOT_PROD _wrap_DST_DOT_PROD ""
extern void (*_wrap_DST_DOT_PROD)(void*);
static void (*x_wrap_DST_DOT_PROD)(void*) = _wrap_DST_DOT_PROD;

void
·_swig_getDST_DOT_PROD(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DST_DOT_PROD, &p);
}



#pragma dynimport _wrap_DST_COVARIANCE _wrap_DST_COVARIANCE ""
extern void (*_wrap_DST_COVARIANCE)(void*);
static void (*x_wrap_DST_COVARIANCE)(void*) = _wrap_DST_COVARIANCE;

void
·_swig_getDST_COVARIANCE(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DST_COVARIANCE, &p);
}



#pragma dynimport _wrap_DST_MANHATTAN _wrap_DST_MANHATTAN ""
extern void (*_wrap_DST_MANHATTAN)(void*);
static void (*x_wrap_DST_MANHATTAN)(void*) = _wrap_DST_MANHATTAN;

void
·_swig_getDST_MANHATTAN(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DST_MANHATTAN, &p);
}



#pragma dynimport _wrap_DST_NULL _wrap_DST_NULL ""
extern void (*_wrap_DST_NULL)(void*);
static void (*x_wrap_DST_NULL)(void*) = _wrap_DST_NULL;

void
·_swig_getDST_NULL(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_DST_NULL, &p);
}



#pragma dynimport _wrap_basicDistFunctions_get _wrap_basicDistFunctions_get ""
extern void (*_wrap_basicDistFunctions_get)(void*);
static void (*x_wrap_basicDistFunctions_get)(void*) = _wrap_basicDistFunctions_get;

void
·GetBasicDistFunctions(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_basicDistFunctions_get, &p);
}



#pragma dynimport _wrap_OBT_NORMAL _wrap_OBT_NORMAL ""
extern void (*_wrap_OBT_NORMAL)(void*);
static void (*x_wrap_OBT_NORMAL)(void*) = _wrap_OBT_NORMAL;

void
·_swig_getOBT_NORMAL(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OBT_NORMAL, &p);
}



#pragma dynimport _wrap_OBT_SUPPORT _wrap_OBT_SUPPORT ""
extern void (*_wrap_OBT_SUPPORT)(void*);
static void (*x_wrap_OBT_SUPPORT)(void*) = _wrap_OBT_SUPPORT;

void
·_swig_getOBT_SUPPORT(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OBT_SUPPORT, &p);
}



#pragma dynimport _wrap_OBT_OUTLIER _wrap_OBT_OUTLIER ""
extern void (*_wrap_OBT_OUTLIER)(void*);
static void (*x_wrap_OBT_OUTLIER)(void*) = _wrap_OBT_OUTLIER;

void
·_swig_getOBT_OUTLIER(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_OBT_OUTLIER, &p);
}



#pragma dynimport _wrap_Flame_simtype_set _wrap_Flame_simtype_set ""
extern void (*_wrap_Flame_simtype_set)(void*);
static void (*x_wrap_Flame_simtype_set)(void*) = _wrap_Flame_simtype_set;

void
·_swig_wrap_Flame_simtype_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_simtype_set, &p);
}



#pragma dynimport _wrap_Flame_simtype_get _wrap_Flame_simtype_get ""
extern void (*_wrap_Flame_simtype_get)(void*);
static void (*x_wrap_Flame_simtype_get)(void*) = _wrap_Flame_simtype_get;

void
·_swig_wrap_Flame_simtype_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_simtype_get, &p);
}



#pragma dynimport _wrap_Flame_N_set _wrap_Flame_N_set ""
extern void (*_wrap_Flame_N_set)(void*);
static void (*x_wrap_Flame_N_set)(void*) = _wrap_Flame_N_set;

void
·_swig_wrap_Flame_N_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_N_set, &p);
}



#pragma dynimport _wrap_Flame_N_get _wrap_Flame_N_get ""
extern void (*_wrap_Flame_N_get)(void*);
static void (*x_wrap_Flame_N_get)(void*) = _wrap_Flame_N_get;

void
·_swig_wrap_Flame_N_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_N_get, &p);
}



#pragma dynimport _wrap_Flame_K_set _wrap_Flame_K_set ""
extern void (*_wrap_Flame_K_set)(void*);
static void (*x_wrap_Flame_K_set)(void*) = _wrap_Flame_K_set;

void
·_swig_wrap_Flame_K_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_K_set, &p);
}



#pragma dynimport _wrap_Flame_K_get _wrap_Flame_K_get ""
extern void (*_wrap_Flame_K_get)(void*);
static void (*x_wrap_Flame_K_get)(void*) = _wrap_Flame_K_get;

void
·_swig_wrap_Flame_K_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_K_get, &p);
}



#pragma dynimport _wrap_Flame_KMAX_set _wrap_Flame_KMAX_set ""
extern void (*_wrap_Flame_KMAX_set)(void*);
static void (*x_wrap_Flame_KMAX_set)(void*) = _wrap_Flame_KMAX_set;

void
·_swig_wrap_Flame_KMAX_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_KMAX_set, &p);
}



#pragma dynimport _wrap_Flame_KMAX_get _wrap_Flame_KMAX_get ""
extern void (*_wrap_Flame_KMAX_get)(void*);
static void (*x_wrap_Flame_KMAX_get)(void*) = _wrap_Flame_KMAX_get;

void
·_swig_wrap_Flame_KMAX_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_KMAX_get, &p);
}



#pragma dynimport _wrap_Flame_graph_set _wrap_Flame_graph_set ""
extern void (*_wrap_Flame_graph_set)(void*);
static void (*x_wrap_Flame_graph_set)(void*) = _wrap_Flame_graph_set;

void
·_swig_wrap_Flame_graph_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_graph_set, &p);
}



#pragma dynimport _wrap_Flame_graph_get _wrap_Flame_graph_get ""
extern void (*_wrap_Flame_graph_get)(void*);
static void (*x_wrap_Flame_graph_get)(void*) = _wrap_Flame_graph_get;

void
·_swig_wrap_Flame_graph_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_graph_get, &p);
}



#pragma dynimport _wrap_Flame_dists_set _wrap_Flame_dists_set ""
extern void (*_wrap_Flame_dists_set)(void*);
static void (*x_wrap_Flame_dists_set)(void*) = _wrap_Flame_dists_set;

void
·_swig_wrap_Flame_dists_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_dists_set, &p);
}



#pragma dynimport _wrap_Flame_dists_get _wrap_Flame_dists_get ""
extern void (*_wrap_Flame_dists_get)(void*);
static void (*x_wrap_Flame_dists_get)(void*) = _wrap_Flame_dists_get;

void
·_swig_wrap_Flame_dists_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_dists_get, &p);
}



#pragma dynimport _wrap_Flame_nncounts_set _wrap_Flame_nncounts_set ""
extern void (*_wrap_Flame_nncounts_set)(void*);
static void (*x_wrap_Flame_nncounts_set)(void*) = _wrap_Flame_nncounts_set;

void
·_swig_wrap_Flame_nncounts_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_nncounts_set, &p);
}



#pragma dynimport _wrap_Flame_nncounts_get _wrap_Flame_nncounts_get ""
extern void (*_wrap_Flame_nncounts_get)(void*);
static void (*x_wrap_Flame_nncounts_get)(void*) = _wrap_Flame_nncounts_get;

void
·_swig_wrap_Flame_nncounts_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_nncounts_get, &p);
}



#pragma dynimport _wrap_Flame_weights_set _wrap_Flame_weights_set ""
extern void (*_wrap_Flame_weights_set)(void*);
static void (*x_wrap_Flame_weights_set)(void*) = _wrap_Flame_weights_set;

void
·_swig_wrap_Flame_weights_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_weights_set, &p);
}



#pragma dynimport _wrap_Flame_weights_get _wrap_Flame_weights_get ""
extern void (*_wrap_Flame_weights_get)(void*);
static void (*x_wrap_Flame_weights_get)(void*) = _wrap_Flame_weights_get;

void
·_swig_wrap_Flame_weights_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_weights_get, &p);
}



#pragma dynimport _wrap_Flame_cso_count_set _wrap_Flame_cso_count_set ""
extern void (*_wrap_Flame_cso_count_set)(void*);
static void (*x_wrap_Flame_cso_count_set)(void*) = _wrap_Flame_cso_count_set;

void
·_swig_wrap_Flame_cso_count_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_cso_count_set, &p);
}



#pragma dynimport _wrap_Flame_cso_count_get _wrap_Flame_cso_count_get ""
extern void (*_wrap_Flame_cso_count_get)(void*);
static void (*x_wrap_Flame_cso_count_get)(void*) = _wrap_Flame_cso_count_get;

void
·_swig_wrap_Flame_cso_count_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_cso_count_get, &p);
}



#pragma dynimport _wrap_Flame_obtypes_set _wrap_Flame_obtypes_set ""
extern void (*_wrap_Flame_obtypes_set)(void*);
static void (*x_wrap_Flame_obtypes_set)(void*) = _wrap_Flame_obtypes_set;

void
·_swig_wrap_Flame_obtypes_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_Flame_obtypes_set, &p);
}



#pragma dynimport _wrap_Flame_obtypes_get _wrap_Flame_obtypes_get ""
extern void (*_wrap_Flame_obtypes_get)(void*);
static void (*x_wrap_Flame_obtypes_get)(void*) = _wrap_Flame_obtypes_get;

void
·_swig_wrap_Flame_obtypes_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + (2 * SWIG_PARM_SIZE)];
} p)

{
  runtime·cgocall(x_wrap_Flame_obtypes_get, &p);
}



#pragma dynimport _wrap_Flame_fuzzyships_set _wrap_Flame_fuzzyships_set ""
extern void (*_wrap_Flame_fuzzyships_set)(void*);
static void (*x_wrap_Flame_fuzzyships_set)(void*) = _wrap_Flame_fuzzyships_set;

void
·_swig_wrap_Flame_fuzzyships_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_fuzzyships_set, &p);
}



#pragma dynimport _wrap_Flame_fuzzyships_get _wrap_Flame_fuzzyships_get ""
extern void (*_wrap_Flame_fuzzyships_get)(void*);
static void (*x_wrap_Flame_fuzzyships_get)(void*) = _wrap_Flame_fuzzyships_get;

void
·_swig_wrap_Flame_fuzzyships_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_fuzzyships_get, &p);
}



#pragma dynimport _wrap_Flame_count_set _wrap_Flame_count_set ""
extern void (*_wrap_Flame_count_set)(void*);
static void (*x_wrap_Flame_count_set)(void*) = _wrap_Flame_count_set;

void
·_swig_wrap_Flame_count_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_count_set, &p);
}



#pragma dynimport _wrap_Flame_count_get _wrap_Flame_count_get ""
extern void (*_wrap_Flame_count_get)(void*);
static void (*x_wrap_Flame_count_get)(void*) = _wrap_Flame_count_get;

void
·_swig_wrap_Flame_count_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_count_get, &p);
}



#pragma dynimport _wrap_Flame_clusters_set _wrap_Flame_clusters_set ""
extern void (*_wrap_Flame_clusters_set)(void*);
static void (*x_wrap_Flame_clusters_set)(void*) = _wrap_Flame_clusters_set;

void
·_swig_wrap_Flame_clusters_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_clusters_set, &p);
}



#pragma dynimport _wrap_Flame_clusters_get _wrap_Flame_clusters_get ""
extern void (*_wrap_Flame_clusters_get)(void*);
static void (*x_wrap_Flame_clusters_get)(void*) = _wrap_Flame_clusters_get;

void
·_swig_wrap_Flame_clusters_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_clusters_get, &p);
}



#pragma dynimport _wrap_Flame_distfunc_set _wrap_Flame_distfunc_set ""
extern void (*_wrap_Flame_distfunc_set)(void*);
static void (*x_wrap_Flame_distfunc_set)(void*) = _wrap_Flame_distfunc_set;

void
·_swig_wrap_Flame_distfunc_set(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_distfunc_set, &p);
}



#pragma dynimport _wrap_Flame_distfunc_get _wrap_Flame_distfunc_get ""
extern void (*_wrap_Flame_distfunc_get)(void*);
static void (*x_wrap_Flame_distfunc_get)(void*) = _wrap_Flame_distfunc_get;

void
·_swig_wrap_Flame_distfunc_get(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_distfunc_get, &p);
}



#pragma dynimport _wrap_new_Flame _wrap_new_Flame ""
extern void (*_wrap_new_Flame)(void*);
static void (*x_wrap_new_Flame)(void*) = _wrap_new_Flame;

void
·_swig_wrap_new_Flame(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_new_Flame, &p);
}



#pragma dynimport _wrap_delete_Flame _wrap_delete_Flame ""
extern void (*_wrap_delete_Flame)(void*);
static void (*x_wrap_delete_Flame)(void*) = _wrap_delete_Flame;

void
·_swig_wrap_delete_Flame(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_delete_Flame, &p);
}



#pragma dynimport _wrap_Flame_New _wrap_Flame_New ""
extern void (*_wrap_Flame_New)(void*);
static void (*x_wrap_Flame_New)(void*) = _wrap_Flame_New;

void
·_swig_wrap_Flame_New(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_New, &p);
}



#pragma dynimport _wrap_Flame_Clear _wrap_Flame_Clear ""
extern void (*_wrap_Flame_Clear)(void*);
static void (*x_wrap_Flame_Clear)(void*) = _wrap_Flame_Clear;

void
·_swig_wrap_Flame_Clear(struct {
  uint8 x[SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_Clear, &p);
}



#pragma dynimport _wrap_Flame_SetDataMatrix _wrap_Flame_SetDataMatrix ""
extern void (*_wrap_Flame_SetDataMatrix)(void*);
static void (*x_wrap_Flame_SetDataMatrix)(void*) = _wrap_Flame_SetDataMatrix;

void
·_swig_wrap_Flame_SetDataMatrix(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_SetDataMatrix, &p);
}



#pragma dynimport _wrap_Flame_SetDistMatrix _wrap_Flame_SetDistMatrix ""
extern void (*_wrap_Flame_SetDistMatrix)(void*);
static void (*x_wrap_Flame_SetDistMatrix)(void*) = _wrap_Flame_SetDistMatrix;

void
·_swig_wrap_Flame_SetDistMatrix(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_SetDistMatrix, &p);
}



#pragma dynimport _wrap_Flame_DefineSupports _wrap_Flame_DefineSupports ""
extern void (*_wrap_Flame_DefineSupports)(void*);
static void (*x_wrap_Flame_DefineSupports)(void*) = _wrap_Flame_DefineSupports;

void
·_swig_wrap_Flame_DefineSupports(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_DefineSupports, &p);
}



#pragma dynimport _wrap_Flame_LocalApproximation _wrap_Flame_LocalApproximation ""
extern void (*_wrap_Flame_LocalApproximation)(void*);
static void (*x_wrap_Flame_LocalApproximation)(void*) = _wrap_Flame_LocalApproximation;

void
·_swig_wrap_Flame_LocalApproximation(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_LocalApproximation, &p);
}



#pragma dynimport _wrap_Flame_MakeClusters _wrap_Flame_MakeClusters ""
extern void (*_wrap_Flame_MakeClusters)(void*);
static void (*x_wrap_Flame_MakeClusters)(void*) = _wrap_Flame_MakeClusters;

void
·_swig_wrap_Flame_MakeClusters(struct {
  uint8 x[SWIG_PARM_SIZE + SWIG_PARM_SIZE];
} p)

{
  runtime·cgocall(x_wrap_Flame_MakeClusters, &p);
}



